language: python
python:
  - "3.5"
services:
  -postgresql
# command to install dependencies
install: 
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - psql -c 'create database stack_dev;' -U postgres
  - psql -c 'create database stack_test;' -U postgres
# command to run tests
script: 
  nosetests --with-coverage --cover-package=app
after_success:
  - coveralls
  